FROM mcr.microsoft.com/playwright:v1.62.1-noble
WORKDIR /app

COPY client/package.json client/package-lock.json ./

RUN npm ci

COPY client/playwright.config.js ./
COPY client/tests ./tests

CMD ["npx", "playwright", "test"]